// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC29brR6T9gAftZdOE7zbr9LIp_-h35KTs',
    appId: '1:626813455341:web:bcfecda0f79c8772a8f5e4',
    messagingSenderId: '626813455341',
    projectId: 'gonogo-2cbd3',
    authDomain: 'gonogo-2cbd3.firebaseapp.com',
    storageBucket: 'gonogo-2cbd3.firebasestorage.app',
    measurementId: 'G-KDB7T39N5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaKtNAwIrZccySstkUBObrp9pn9dTUo3w',
    appId: '1:626813455341:android:3fa94b737dfd0eb3a8f5e4',
    messagingSenderId: '626813455341',
    projectId: 'gonogo-2cbd3',
    storageBucket: 'gonogo-2cbd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqz33-25c7UGQmaF2K3FZ7ZGARWj-BXI0',
    appId: '1:626813455341:ios:80ba41db64f05da1a8f5e4',
    messagingSenderId: '626813455341',
    projectId: 'gonogo-2cbd3',
    storageBucket: 'gonogo-2cbd3.firebasestorage.app',
    iosBundleId: 'com.example.gonogoNovo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqz33-25c7UGQmaF2K3FZ7ZGARWj-BXI0',
    appId: '1:626813455341:ios:5593cc7ea14829e4a8f5e4',
    messagingSenderId: '626813455341',
    projectId: 'gonogo-2cbd3',
    storageBucket: 'gonogo-2cbd3.firebasestorage.app',
    iosBundleId: 'com.example.gonogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC29brR6T9gAftZdOE7zbr9LIp_-h35KTs',
    appId: '1:626813455341:web:10fe735d23ed6d88a8f5e4',
    messagingSenderId: '626813455341',
    projectId: 'gonogo-2cbd3',
    authDomain: 'gonogo-2cbd3.firebaseapp.com',
    storageBucket: 'gonogo-2cbd3.firebasestorage.app',
    measurementId: 'G-MQK4WNZRW8',
  );
}
